services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fitbody_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fitbody_db
      SPRING_DATASOURCE_USERNAME: fitbody_user
      SPRING_DATASOURCE_PASSWORD: fitbody_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  db:
    image: postgres:15
    container_name: fitbody_db
    environment:
      POSTGRES_DB: fitbody_db
      POSTGRES_USER: fitbody_user
      POSTGRES_PASSWORD: fitbody_password
    ports:
      - "5773:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  db_data:
